'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _1_doticket

    '''<summary>
    '''TrxCustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxCustomerID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxNumberID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxNumberID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxThreadID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxThreadID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxChannel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxChannel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxTicketNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxTicketNumber As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxStatus As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HD_API_Gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HD_API_Gender As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HD_API_NomorPolis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HD_API_NomorPolis As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_Layer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_Layer As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxNomorWhatsApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxNomorWhatsApp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxPriority As Global.System.Web.UI.WebControls.HiddenField
End Class
